name: Add Copyright Headers

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  add_copyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/copywrite@v1
        env:
          COPYRIGHT_LICENSE: "Apache 2.0"
        with:
          command: headers
          paths: |
            "**/*.go"
